#!/usr/bin/env python3
"""
gen_xs_blackbox.py
Extracts the XSTop port list from XSTop.v and generates a SystemVerilog
blackbox declaration (module header with ports, no body).

Usage:
    python3 gen_xs_blackbox.py --xs-top path/to/XSTop.v --output path/to/XSTop_bb.sv
"""

import argparse
import re
import sys


def find_module_ports(vfile: str) -> list[str]:
    """Scan vfile for 'module XSTop(' and extract the port list lines."""
    port_lines = []
    in_module = False
    paren_depth = 0

    with open(vfile, 'r') as f:
        for line in f:
            if not in_module:
                if re.search(r'\bmodule\s+XSTop\s*\(', line):
                    in_module = True
                    # Count opening paren on this line
                    paren_depth += line.count('(') - line.count(')')
                    port_lines.append(line.rstrip())
                continue

            # Inside module header
            paren_depth += line.count('(') - line.count(')')
            port_lines.append(line.rstrip())

            if paren_depth <= 0:
                # We've closed the port list ')'
                break

    return port_lines


def generate_blackbox(port_lines: list[str]) -> str:
    """Wrap port lines in a blackbox module declaration."""
    lines = []
    lines.append('// XSTop_bb.sv')
    lines.append('// Auto-generated blackbox declaration for XSTop.')
    lines.append('// Generated by gen_xs_blackbox.py — do not edit manually.')
    lines.append('')
    lines.append('`ifndef XSTOP_BB_SV')
    lines.append('`define XSTOP_BB_SV')
    lines.append('')

    # Emit the module header exactly as extracted, then add empty body
    for l in port_lines:
        lines.append(l)

    # Close with empty body
    lines.append('  // blackbox: no implementation')
    lines.append('endmodule')
    lines.append('')
    lines.append('`endif // XSTOP_BB_SV')
    lines.append('')

    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(
        description='Generate a SystemVerilog blackbox for XSTop from XSTop.v')
    parser.add_argument('--xs-top', required=True,
                        help='Path to XSTop.v (Chisel-generated)')
    parser.add_argument('--output', required=True,
                        help='Output path for the blackbox .sv file')
    args = parser.parse_args()

    print(f'Reading {args.xs_top} ...')
    port_lines = find_module_ports(args.xs_top)
    if not port_lines:
        print('ERROR: Could not find "module XSTop(" in the input file.',
              file=sys.stderr)
        sys.exit(1)

    print(f'Found {len(port_lines)} lines in XSTop port list.')
    bb = generate_blackbox(port_lines)

    with open(args.output, 'w') as f:
        f.write(bb)
    print(f'Blackbox written to {args.output}')


if __name__ == '__main__':
    main()
